Update geopm_agent_frequency_map man page
geopm/geopm pull request #1069
Opened 2020-04-24 22:27 UTC by cmcantalupo

- Also changes behavior of the geopmagent command line interpreter to support strings
  for region hashes in the policy vector.
- Related to #1049

2020-04-24 22:50 UTC, dianarg requested changes
Seems pretty close; a few typos.  One feature that may be confusing is that NAN for core frequency means sticker, but NAN for uncore means operate within the normal range.  Does it make sense for NAN to mean the same thing for the core frequency?  Then we don't need to worry about whether to make max or sticker the default.

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +The frequency map agent selects CPU frequency in response to changes
selects -> adjusts?

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +policy provides a map from a GEOPM region hash to a CPU frequency, see
, --> ;

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +frequency map is provided.
this is useful for experiments sweeping over a range of core and/or uncore frequency

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +                  sticker frequency is selected for this parameter if
this means that running with this agent with NAN policy only could have lower performance than the monitor.

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +            representation of the 32 bit integer generated by the hash
32-bit

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +limit frequency changes to 500 Hz.
limits the rate of frequency changes?  could these be in the same units?

2020-04-24 22:50 UTC, dianarg commented on ronn/geopm_agent_frequency_map.7.ronn
> +      {"FREQ_MIN": 3500000000, "FREQ_MAX": 2400000000}
fix policy names

2020-04-27 20:55 UTC, cmcantalupo reviewed
Updated the branch and I think I've addressed all concerns.

2020-04-27 20:55 UTC, cmcantalupo commented on ronn/geopm_agent_frequency_map.7.ronn
> +      {"FREQ_MIN": 3500000000, "FREQ_MAX": 2400000000}
yuck

2020-04-27 20:55 UTC, cmcantalupo commented on ronn/geopm_agent_frequency_map.7.ronn
> +limit frequency changes to 500 Hz.
Maybe overkill, but these two numbers are the same...just inverted.

2020-04-27 20:58 UTC, dianarg approved these changes

2020-04-28 15:34 UTC, merged