Add base class and two implementations of record filters
geopm/geopm pull request #1137
Opened 2020-06-01 23:54 UTC by cmcantalupo

- Add doxygen comments to filter classes
- Add unit test for EpochRecordFilter
- Add unit tests for the ProxyEpochRecordFilter

2020-06-01 23:58 UTC, cmcantalupo commented on test/ProxyEpochRecordFilterTest.cpp
> +    geopm::ProxyEpochRecordFilter perf(0XAULL, 1, 0);
0xAULL for consistency.

2020-06-02 00:19 UTC, dianarg requested changes

2020-06-02 00:19 UTC, dianarg commented on src/EpochRecordFilter.hpp
> +            /// @return Vector of lenth one containing input value if
length

2020-06-02 00:19 UTC, dianarg commented on src/ProxyEpochRecordFilter.cpp
> +        if (m_proxy_hash > 1ULL <<32) {
maybe a comment or name for this magic number.  hopefully we have some documentation about this somewhere

2020-06-02 00:19 UTC, dianarg commented on src/ProxyEpochRecordFilter.cpp
> +                ApplicationSampler::m_record_s epoch_event(record);
kind of a nit, but assignment would be nicer than copy constructor

2020-06-02 00:19 UTC, dianarg commented on src/EpochRecordFilter.hpp
> +            /// @param record The update value to be filtered.
I think these should be `@param [in] name`.  more below.

2020-06-02 00:19 UTC, dianarg commented on src/ProxyEpochRecordFilter.hpp
> +            /// @param region_hash The hash for the region that will
[in]

2020-06-02 00:19 UTC, dianarg commented on test/ProxyEpochRecordFilterTest.cpp
> +    perf.filter(record);
assert size == 0 here ?

2020-06-02 16:50 UTC, dianarg approved these changes
LGTM

2020-06-03 16:20 UTC, closed without merging