Public lhlawson nvml board agent
geopm/geopm pull request #1294
Opened 2020-09-10 02:45 UTC by lhlawson

This PR is a follow on to PR #1246.  It focuses on using the NVMLIOGroup to impact workloads running on NVML devices.  This PR introduces a new agent, the NVMLBoardUtilizationAgent, and introduces READMEs for two NVML enabled workloads (HACC and LAMMPS) as well as policies to be used with those workloads.  This agent is meant to provide both an example of NVML usage in agents, and demonstrate some simple utilization based energy saving approaches in heterogeneous systems.

Summary of change:
- Addition of the NVMLBoardUtilizationAgent, an accelerator focused agent that monitors NVML::UTILIZATION_ACCELERATOR and changes the Accelerator and Socket frequencies based upon a series of thresholds defined by the user defined policy.  All monitoring and controls are handled at the board level.
- Addition of NVMLBoardUtilizationAgentTest for testing base agent functionality
- Addition of examples/accelerator_examples folder to separate accelerator enabled workloads from their x86 counterparts
- Addition of two default policies for the NVMLBoardUtilizationAgent - policy_singlethresh.json and policy_doublethresh.json.
- Addition of READMEs for two NVML workloads: HACC and LAMMPS
- Addition of two polices for each workload, named in the format policy_<workload>-<double/single>thresh.json.  

High Level Overview:
![image](https://user-images.githubusercontent.com/23505009/92675376-1525aa80-f2d4-11ea-91b0-24cebfa87b7e.png)

2020-09-30 21:37 UTC, dianarg reviewed
Partial review - more to look at still

2020-09-30 21:37 UTC, dianarg commented on examples/accelerator_examples/hacc/README
> +    https://asc.llnl.gov/coral-2-benchmarks/supplementary-material.php
Please check this link; it seems to have moved.

2020-09-30 21:37 UTC, dianarg commented on examples/accelerator_examples/hacc/README
> +If using newer versions of the cuda toolkit (10+), some updates may be required.  Most notably:
CUDA
check if this also needs (R)

2020-09-30 21:37 UTC, dianarg commented on scripts/test/TestAgent.py
> +    def get_config_value(key):
I thought there was a helper function for this.  See if you can find it or remind me to check it later.

2020-09-30 21:37 UTC, dianarg commented on scripts/test/TestAgent.py
> +                    return line[len(line_start):-len(line_end)]
use result with default instead of early return

2020-09-30 21:37 UTC, dianarg commented on Makefile.am
> +                                 src/NVMLBoardUtilizationAgent.cpp \
Let's discuss the name as the group.  Maybe BoardUtilizationAgent? AcceleratorUtilizationAgent?

2020-09-30 21:37 UTC, dianarg commented on src/Agent.cpp
> -#include "config.h"
ok to leave at the top for this one only

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +                              {"FREQUENCY", {}}
Some name that distinguishes this from the CPU frequency signal, and distinguishes signal from control.  The FREQUENCY alias in MSRIOGroup is deprecated and will be replaced with CPU_FREQUENCY_STATUS and CPU_FREQUENCY_CONTROL.

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        , m_signal_available({{"NVML::FREQUENCY", {}},
Maybe just m_signal.  'available' is misleading

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +                                        std::vector<double>& out_sample)
indentation

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +                                    std::vector<std::vector<double> >& out_policy)
indentation

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        assert(in_policy.size() == M_NUM_POLICY);
use GEOPM_DEBUG_ASSERT (throws exception)

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        return true;
this could be optimized to only return true if the policy changes

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +    //    to corresponding above_thresh_1 values
This might be better in the header.  Also this agent may need its own man page.

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        double utilization_accelerator = m_signal_available.at("NVML::UTILIZATION_ACCELERATOR").m_last_signal;
If this can use aliases instead, does that remove any dependence on NVML (e.g. the name of the agent)?

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +    // Wait for the remaining cycle time to keep Controller loop cadence at 1 second
50ms?

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +    // Wait for the remaining cycle time to keep Controller loop cadence at 1 second
is this agent a candidate (guinea pig) for including control loop cadence as a policy value?  See #576 and #1065

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        int values_idx = 0;
check size of values vector == m_signal_avail.size()

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        for (auto &sv : m_signal_available) {
Kind of a nit: this could be regular for(values_idx = 0.. N) type loop assuming the vectors are the same size.

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        std::vector<std::function<std::string(double)>> trace_formats;
space between `>>` --> `> >`
This is a parsing issue with old versions of gcc

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +                xeon_freq_request != m_signal_available.at("FREQUENCY").m_last_signal) {
use new CPU_FREQUENCY_STATUS alias

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +                freq_ctl_itr = m_control_available.find("FREQUENCY");
CPU_FREQUENCY_CONTROL

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +            if (accel_freq_request != m_signal_available.at("NVML::FREQUENCY").m_last_signal ||
same comment on alias vs NVML-specific name

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        assert(out_sample.size() == M_NUM_SAMPLE);
GEOPM_DEBUG_ASSERT

2020-09-30 21:37 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.cpp
> +        assert(in_policy.size() == M_NUM_POLICY);
GEOPM_DEBUG_ASSERT

2020-10-01 00:01 UTC, dianarg requested changes
An implementation of Agent::enforce_policy() is missing.  I'm not sure what we want to do in that case (no controller is running, but the agent is being used to apply a "static policy" to the nodes).

2020-10-01 00:01 UTC, dianarg commented on scripts/test/TestAgent.py
> +    def get_config_value(key):
There is one in integration/test/util.py, get_config_value.  Unfortunately test.util brings in a dependency on the launcher, but I think this function could be separated out.  If this gest merged without that change (with this code repeated here) please open a issue to fix it later.

2020-10-01 00:01 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.hpp
> +#include <nvml.h>
hopefully not needed?

2020-10-01 00:01 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.hpp
> +    /// @brief Agent
add description

2020-10-01 00:01 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.hpp
> +            struct signal
The usual pattern for these internal structs is something like `m_signal_s`.  Also prevents confusion with std::signal

2020-10-01 00:01 UTC, dianarg commented on src/NVMLBoardUtilizationAgent.hpp
> +            double m_accelerator_frequency_requests;
Some of these are missing from the constructor initializer list

2023-07-26 17:23 UTC, lhlawson commented
Replaced by the existing GPU CA Agent

2023-07-26 17:23 UTC, closed without merging