Enable user control of process pinning in launcher
geopm/geopm pull request #1585
Opened 2021-03-22 23:49 UTC by cmcantalupo

This adds a new command line option to geopmlaunch --geopm-affinity-disable which will allow the user to control all cpu affinity options for the underlying launch command.  This is coupled with a change to the ApplicationSampler::connect() method that affinitizes the thread using the sampler to a core not used by the application.

TODO:  Update launcher documentation to reflect this feature

2021-03-23 18:53 UTC, cmcantalupo commented on src/ApplicationSampler.cpp
> +        for (int cpu_idx = m_num_cpu - 1; cpu_idx != -1; --cpu_idx) {
Could land the controller on hyperthread of application if it is using the last core, but not the hyperthread of the last core.

2021-03-23 19:03 UTC, cmcantalupo commented on src/ApplicationSampler.cpp
> +        std::vector<bool> cpu_enabled(m_num_cpu, false);
cpu_enabled -> sampler_cpu_set

2021-03-25 18:46 UTC, bgeltz requested changes

2021-03-25 18:46 UTC, bgeltz commented on README
> +automatically affinitize iteself to the highest indexed core not used
```suggestion
automatically affinitize itself to the highest indexed core not used
```

2021-03-25 18:46 UTC, bgeltz commented on src/ApplicationSampler.cpp
> +        (void)sched_setaffinity(0, CPU_ALLOC_SIZE(m_num_cpu), sampler_cpu_mask.get());
Don't ignore the rc.

2021-03-25 18:46 UTC, bgeltz commented on test/ApplicationSamplerTest.cpp
> +{
Comments please to explain the numbering here between physical cores and linux logical cpus.

2021-03-25 22:04 UTC, bgeltz approved these changes, later dismissed

2021-03-25 22:58 UTC, bgeltz approved these changes

2021-03-25 23:15 UTC, merged