Create a python controller that can be used with pio
geopm/geopm pull request #1795
Opened 2021-08-18 22:37 UTC by cmcantalupo

2021-08-18 23:15 UTC, bgeltz requested changes

2021-08-18 23:15 UTC, bgeltz commented on service/geopmdpy/session.py
> +from . import runtime
```suggestion
from . import runtime

```

2021-08-18 23:15 UTC, bgeltz commented on service/geopmdpy/runtime.py
> +            for loop_idx in TimedLoop(self._num_update, self._update_period):
Use 0 to mean infinite loop?

2021-08-18 23:15 UTC, bgeltz commented on service/geopmdpy/runtime.py
> +            result = [ee - bb for bb, ee in zip(signals_begin, signals_end)]
A reporter method would be nice.

2021-08-18 23:15 UTC, bgeltz commented on service/geopmdpy/runtime.py
> +            result = [ee - bb for bb, ee in zip(signals_begin, signals_end)]
result = agent.generateReport()

2021-08-18 23:15 UTC, bgeltz commented on service/test/test_controller.py
> +        return [("INSTRUCTIONS_RETIRED", geopmdpy.topo.DOMAIN_PACKAGE, 0)]
Including TIME would help.

2021-08-18 23:15 UTC, bgeltz commented on service/test/test_controller.sh
> +exit 0
Delete this file.

2021-08-18 23:15 UTC, bgeltz commented on service/Makefile.am
> +             test/test_controller.sh \
```suggestion
```

2021-08-19 00:11 UTC, bgeltz approved these changes

2021-08-19 00:57 UTC, alawibaba commented
I had to make a couple of small changes to get through the test. Also since we took away the sh script (which admittedly I forgot to do correctly), should we dump a usage message if parameters are absent?

2021-08-19 16:09 UTC, cmcantalupo commented on service/test/test_controller.py
> +        sys.stderr.print(help_msg)
print -> write...testing is tbd

2021-08-19 16:53 UTC, bgeltz approved these changes

2021-08-19 17:06 UTC, merged