Implement POSIXSignal and tests for it
geopm/geopm pull request #1959
Opened 2021-10-21 04:18 UTC by Krebrov001

- Relates to #1856 from github issues
- Fixes #1856 change request from github issues.

This pull request fleshes out the class POSIXSignal, which is a wrapper around the POSIX signal classes that are used by the GEOPM, and also adds comprlehensive units for this class.

2021-10-21 14:09 UTC, cmcantalupo commented on service/test/POSIXSignalTest.cpp
> +
```suggestion
```

2021-10-21 14:11 UTC, cmcantalupo commented on service/src/POSIXSignal.cpp
> +        }
```suggestion
```

2021-10-21 14:11 UTC, cmcantalupo commented on service/test/POSIXSignalTest.cpp
> +        //check_return(is_in_set, "sigismember()");
```suggestion
```

2021-10-21 14:13 UTC, cmcantalupo commented on service/test/POSIXSignalTest.cpp
> +    EXPECT_EQ(0, memcmp(&sigset, &dummy, sizeof(sigset_t)));
This is making an assumption about the composition of sigset_t.  If it is true, my guess is it will not change in the future, so maybe this is okay.

2021-10-21 14:14 UTC, cmcantalupo commented on service/src/POSIXSignal.hpp
> +                                       const struct timespec *timeout) const = 0;
The BatchServer and BatchClient are not using these methods,so we may consider deleting them.

2021-10-21 14:17 UTC, cmcantalupo commented on service/test/Makefile.mk
> +              test/gtest_links/POSIXSignalTest.sig_action_EAULT \
```suggestion
```

2021-10-21 14:18 UTC, cmcantalupo commented on service/test/POSIXSignalTest.cpp
> +    m_posix_sig->sig_proc_mask(SIG_SETMASK, &original_sigset, nullptr);
Please add save/restore feature to SetUp()/TearDown() for the process block mask.

2021-10-21 14:19 UTC, cmcantalupo reviewed
A few comments, but generally looks great!  Thanks @Krebrov001

2021-10-21 18:11 UTC, bgeltz requested changes

2021-10-21 18:11 UTC, bgeltz commented on service/src/POSIXSignal.cpp
> +#include <cerrno>
```suggestion
#include "config.h"

#include <cerrno>

#include "POSIXSignal.hpp"
#include "geopm/Exception.hpp"
#include "geopm/Helper.hpp"
```

We typically put the headers in this order.  "config.h" is always first in case it defines anything that's needed in a lower header.  Next is any system includes, and finally any other GEOPM includes are last.

2021-10-21 18:11 UTC, bgeltz commented on service/src/POSIXSignal.hpp
> +            virtual void POSIXSignalImp::sig_suspend(const sigset_t* mask) const = 0;
```suggestion
            virtual void sig_suspend(const sigset_t *mask) const = 0;
```

2021-10-21 18:11 UTC, bgeltz commented on service/src/POSIXSignal.cpp
> +    void POSIXSignalImp::sig_proc_mask(int how, const sigset_t* set, sigset_t* oldset) const
```suggestion
    void POSIXSignalImp::sig_proc_mask(int how, const sigset_t *set, sigset_t *oldset) const
```

2021-10-21 18:11 UTC, bgeltz commented on service/src/POSIXSignal.hpp
> +            virtual void sig_proc_mask(int how, const sigset_t* set, sigset_t* oldset) const = 0;
```suggestion
            virtual void sig_proc_mask(int how, const sigset_t *set, sigset_t *oldset) const = 0;
```

2021-10-21 18:11 UTC, bgeltz commented on service/src/POSIXSignal.hpp
> +            void sig_proc_mask(int how, const sigset_t* set, sigset_t* oldset) const override;
```suggestion
            void sig_proc_mask(int how, const sigset_t *set, sigset_t *oldset) const override;
```

2021-10-21 18:11 UTC, bgeltz commented on service/src/POSIXSignal.hpp
> +            void sig_suspend(const sigset_t* mask) const override;
```suggestion
            void sig_suspend(const sigset_t *mask) const override;
```

2021-10-21 18:11 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +#include "POSIXSignal.hpp"
Move this down under the system includes.

2021-10-21 18:11 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +        std::set<int> convert_sigset(const sigset_t& the_sigset);
```suggestion
        std::set<int> convert_sigset(const sigset_t &the_sigset);
```

2021-10-21 18:11 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +std::set<int> POSIXSignalTest::convert_sigset(const sigset_t& the_sigset)
```suggestion
std::set<int> POSIXSignalTest::convert_sigset(const sigset_t &the_sigset)
```

2021-10-21 18:11 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +    //struct sigaction newact;
```suggestion
```

2021-10-21 18:11 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +    // https://stackoverflow.com/q/20052674
```suggestion
```
I don't think we want stackoverflow links in the code.  Thoughts @cmcantalupo ?

2021-10-21 21:30 UTC, cmcantalupo commented on service/test/POSIXSignalTest.cpp
> +    // https://stackoverflow.com/q/20052674
I agree, lets remove.  Also @Krebrov001, please be sure that any code in this PR is an original work.

2021-10-21 22:45 UTC, Krebrov001 commented
> I agree, lets remove.  Also @Krebrov001, please be sure that any code in this PR is an original work.   

Using the `std::set_union()` and other such functions working with standard containers was a new thing for me. I have a habit of putting the stackoverflow links for my own reference, so that I can return later to know what a particular code construct was doing. This my code of the test is a completely original work. I was only using the stackoveflow for figuring out how that specific syntax works, once I identified what kind of code I want to write.

2021-10-21 22:49 UTC, Krebrov001 commented on service/test/POSIXSignalTest.cpp
> +    // https://stackoverflow.com/q/20052674
@cmcantalupo @bgeltz  Using the `std::set_union()` and other such functions working with standard containers was a new thing for me. I have a habit of putting the stackoverflow links for my own reference, so that I can return later to know what a particular code construct was doing. This my code of the test is a completely original work. I was only using the stackoveflow for figuring out how that specific syntax works, once I identified what kind of code I want to write.

2021-10-21 22:59 UTC, Krebrov001 commented on service/src/POSIXSignal.cpp
> +        }
@cmcantalupo Sorry for "beating a dead horse", but what was this for again?

2021-10-21 23:06 UTC, Krebrov001 commented on service/src/POSIXSignal.cpp
> +#include <cerrno>
Got it. I will make a note of this and use such practice in future files.

2021-10-21 23:08 UTC, Krebrov001 commented on service/src/POSIXSignal.cpp
> +    void POSIXSignalImp::sig_proc_mask(int how, const sigset_t* set, sigset_t* oldset) const
Change any `*` or `&` to be with the variable name rather than with the data type.

2021-10-21 23:14 UTC, Krebrov001 commented on service/src/POSIXSignal.hpp
> +            virtual void sig_proc_mask(int how, const sigset_t* set, sigset_t* oldset) const = 0;
Change any `*` or `&` to be with the variable name rather than with the data type.

2021-10-22 02:34 UTC, Krebrov001 commented on service/test/POSIXSignalTest.cpp
> +    EXPECT_EQ(0, memcmp(&sigset, &dummy, sizeof(sigset_t)));
removing an assumption about the composition of sigset_t

2021-10-22 05:59 UTC, Krebrov001 commented on service/test/POSIXSignalTest.cpp
> +
I deleted that test completely.
```cpp
/**
 * @test the `act` argument points to memory which is not a valid part of the process address space
 */
TEST_F(POSIXSignalTest, sig_action_EFAULT)
{
    std::string errmsg_expect = "Bad address: POSIXSignal(): POSIX signal function call sigaction() returned an error";
    struct sigaction oldact;
    GEOPM_EXPECT_THROW_MESSAGE(
        m_posix_sig->sig_action(SIGCONT, (const struct sigaction*) ~0ULL, &oldact),
        EFAULT, errmsg_expect);
}
```

This code gives a  **Segmentation fault**. Apparently `sigaction()` does not properly check for `EFAULT` error.

2021-10-22 06:12 UTC, Krebrov001 commented
Now I will rewrite the git history.

2021-10-22 06:58 UTC, Krebrov001 commented
@cmcantalupo @bgeltz  I have addressed all the feedbacks reviews, and I have finally figured out how to rewrite the git history as you wanted.

2021-10-22 18:11 UTC, cmcantalupo commented on service/src/POSIXSignal.cpp
> +        }
`act == null` is a valid use case for getting the current action, and so is `oldact == null`, to set the action without getting the previous action.

2021-10-23 00:01 UTC, bgeltz submitted a review, later dismissed

2021-10-23 00:02 UTC, bgeltz commented
LGTM.  Let's see what Chris thinks.

2021-10-24 02:40 UTC, Krebrov001 commented on service/test/Makefile.mk
> +              test/gtest_links/POSIXSignalTest.sig_suspend_EFAULT \
By the way, I couldn't figure out how to test `sig_suspend_EINTR`.

2021-10-25 17:21 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +        sigset_t backup_sigset;
```suggestion
        sigset_t m_backup_sigset;
```

2021-10-25 17:23 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +    sigprocmask(SIG_SETMASK, nullptr, &backup_sigset);
```suggestion
    sigprocmask(SIG_SETMASK, nullptr, &m_backup_sigset);
```

2021-10-25 17:23 UTC, bgeltz commented on service/test/POSIXSignalTest.cpp
> +    sigprocmask(SIG_SETMASK, &backup_sigset, nullptr);
```suggestion
    sigprocmask(SIG_SETMASK, &m_backup_sigset, nullptr);
```

2021-10-25 17:34 UTC, cmcantalupo approved these changes
LGTM

2021-10-25 17:34 UTC, bgeltz approved these changes

2021-10-25 17:48 UTC, merged