Add security guide to the web page
geopm/geopm pull request #2140
Opened 2022-03-09 20:09 UTC by cmcantalupo

- Relates to #2120

2022-03-10 19:42 UTC, avilcheslopez reviewed
Looks good to me!

2022-03-10 19:42 UTC, avilcheslopez commented on service/docs/source/security.rst
> +to not have excessive permissions.
```suggestion
do not have excessive permissions.
```

2022-03-10 19:42 UTC, avilcheslopez commented on service/docs/source/security.rst
> +it a file descriptor is opened for the path and then checked
Minor note: check grammar around "it".

2022-03-10 19:42 UTC, avilcheslopez commented on service/docs/source/security.rst
> +attempting to setup or use configuration files stored in a secure
```suggestion
attempting to set up or use configuration files stored in a secure
```

2022-03-10 19:42 UTC, avilcheslopez commented on service/docs/source/security.rst
> +that my result in a compromised or misconfigured system. All output
```suggestion
that may result in a compromised or misconfigured system. All output
```

2022-03-10 19:42 UTC, avilcheslopez commented on service/docs/source/security.rst
> +request to through GEOPM DBus interface.  The batch server is accessed
Minor issue: "to through"

2022-03-14 23:40 UTC, bgeltz requested changes

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Fine-grained access management for hardware features
You're mixing upper/lower case for these section titles.  Do you want it like this instead:
```suggestion
Fine-Grained Access Management for Hardware Features
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +programatic solution.
```suggestion
programmatic solution.
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +component that the request applies to.
```suggestion
component to which the request applies.
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Restore control configuration after a writing session ends
```suggestion
Restore Control Configuration After a Writing Session Ends
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +One writing GEOPM session allowed at any time
```suggestion
One Writing GEOPM Session Allowed at Any Time
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +GEOPM Service enforces that at most one writing user session is
```suggestion
The GEOPM Service enforces that at most one writing user session is
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Provide a low latency interface
```suggestion
Provide a Low Latency Interface
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +controls. Requests to read, write or quit are made through a FIFO
```suggestion
controls. Requests to read, write, or quit are made through a FIFO
```

I can't remember if we do serial commas or not.  I think we waffle back and forth on that and one or two spaces after the period.

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Secure restart of the ``geopmd`` daemon process
```suggestion
Secure Restart of the ``geopmd`` Daemon Process
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +interface to provide the PID, UID, and GID of the requesting client.
SERIAL COMMA! xD

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Model Specific Register device driver
```suggestion
Model Specific Register Device Driver
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Intel Speed Select device driver
```suggestion
Intel Speed Select Device Driver
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +as number of cores, base frequency, and which turbo frequencies are
SERIAL COMMA! xD

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +LevelZero sysman library interface
```suggestion
LevelZero Sysman Library Interface
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Nvidia NVML device management library interface
```suggestion
Nvidia NVML Device Management Library Interface
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +GPU devices. These controls and monitors include setting bounds on GPU
```suggestion
GPU devices. These controls and signals include setting bounds on GPU
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Service user data
```suggestion
Service User Data
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +observe the calls, inputs or outputs to the GEOPM Service by other
```suggestion
observe the calls, inputs, or outputs to the GEOPM Service by other
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +System files
```suggestion
System Files
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Inter-process shared memory
```suggestion
Inter-Process Shared Memory
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +FIFO special files
```suggestion
FIFO Special Files
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Systemd DBus interface
```suggestion
Systemd DBus Interface
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +provide traceability to sysadmins about user interactions. This
```suggestion
provide traceability to system administrators about user interactions. This
```

This is the first occurrence of "sysadmin".

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +Malicious input or private output
```suggestion
Malicious Input or Private Output
```

2022-03-14 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +emit private, malicious or malformed data.
```suggestion
emit private, malicious, or malformed data.
```

2022-03-15 16:48 UTC, cmcantalupo commented on service/docs/source/security.rst
> +Fine-grained access management for hardware features
The intent was ^^^^ titles (which are longer) are not capitalized. Will fix.

2022-03-15 18:11 UTC, bgeltz approved these changes

2022-03-15 18:19 UTC, merged