Rename geopm.h to geopm_prof.h, move to base directory
geopm/geopm pull request #2157
Opened 2022-03-14 23:28 UTC by avilcheslopez

- Decoupled service component from geopm.h
- Renamed geopm.h to geopm_prof.h
- Moved geopm_prof.h to base directory
- Updated documentation, build system accordingly

Signed-off-by: Alejandro Vilches <alejandro.vilches@intel.com>

- Relates to #2056 story from github issues
- Fixes #2156 change request from github issues.

_Note_:

Prior to creating a pull request, please see the documentation at
either of the following links:

https://github.com/geopm/geopm/blob/dev/CONTRIBUTING.rst#change-request

https://geopm.github.io/contrib.html#change-request

about the process to change the GEOPM repository.

2022-03-14 23:33 UTC, avilcheslopez commented
OPENS:
- While working on these changes I found that the ``geopm_region_info_s`` struct (defined in ``geopm_prof.h``) is not being used anywhere in the repo (unless I missed/overlooked something). Is this data structure needed?
- As part of the refactor to decouple service from ``geopm.h``, I moved a couple of enums to ``geopm_internal.h`` (as the #2056 indicated). However, some example programs are making use of those enums, and overall it seems like they're meant to be made available to applications. If so, do they really belong in ``geopm_internal.h``?

2022-03-17 00:14 UTC, cmcantalupo approved these changes
LGTM nice work!

2022-03-17 00:15 UTC, cmcantalupo requested changes
https://github.com/geopm/geopm/runs/5578611219?check_suite_focus=true#step:15:1871

The geopm_internal.h must be listed in the SOURCES makefile variable now.

2022-03-17 16:53 UTC, cmcantalupo approved these changes

2022-03-17 17:09 UTC, merged