Add documentation about OBS builds
geopm/geopm pull request #2224
Opened 2022-03-30 23:08 UTC by cmcantalupo

- Fixes #2202

2022-03-30 23:44 UTC, bgeltz requested changes

2022-03-30 23:44 UTC, bgeltz commented on service/docs/Makefile.mk
> +              docs/source/istall.rst \
```suggestion
              docs/source/install.rst \
```

Shouldn't this break the build?

2022-03-30 23:44 UTC, bgeltz commented on service/docs/source/install.rst
> +This is supported by Github Actions, in conjunction with the OpenSUSE
```suggestion
distributions each time certain branches hosted on GitHub are updated.
This is supported by GitHub Actions, in conjunction with the OpenSUSE
```

2022-03-30 23:44 UTC, bgeltz commented on service/docs/source/install.rst
> +
What about dasbus?  Aren't we building some of our dependencies in OBS?
They should be listed here.

2022-03-30 23:44 UTC, bgeltz commented on service/docs/source/install.rst
> +running one of the two commands below:
```suggestion
running one of the two commands below depending on the package management system for the operating system:
```

2022-03-30 23:44 UTC, bgeltz commented on service/docs/source/install.rst
> +depending on the package management system for the operating system.
```suggestion
```

2022-03-30 23:44 UTC, bgeltz commented on service/docs/source/install.rst
> +   zypper addrepo https://download.opensuse.org/repositories/home:/geopm/
```suggestion
   zypper addrepo https://download.opensuse.org/repositories/home:/geopm/15.3/
```

2022-03-31 20:45 UTC, bgeltz approved these changes

2022-03-31 20:45 UTC, merged

2022-03-31 22:49 UTC, cmcantalupo commented
@bensallen This documentation is now posted here:

https://geopm.github.io/install.html