Enable reference counting for multiple nested open sessions
geopm/geopm pull request #2251
Opened 2022-04-08 16:59 UTC by Krebrov001

Enable the PlatformService to support clients having multiple
independent components, which can concurrently use the simgle
connection. Establish a shared pointer esque abstraction over
connections, a one to one mapping with the client process.

Add the reference count to the JSON active session schema.

Signed-off-by: Konstantin Rebrov <konstantin.rebrov@intel.com>

- Relates to #2011 
- Fixes #2011

2022-04-08 23:08 UTC, cmcantalupo commented on service/geopmdpy/system_files.py
> +            int: GLib watch ID to track the session lifetime
```suggestion
            int: The reference count
```

2022-04-08 23:13 UTC, cmcantalupo commented on service/geopmdpy/system_files.py
> +    def set_reference_count(self, client_pid, reference_count):
This interface only seems to be used in the test.  We can leave it, but I'm not sure how it would be used in practice.

2022-04-12 00:11 UTC, bgeltz requested changes
Do we need to add a destructor to the `PlatformService` class that calls `close_session_completely()` for all the client PIDs that are active?  I expected to see this chunk of code somewhere.

2022-04-12 00:11 UTC, bgeltz commented on service/geopmdpy/service.py
> +        # if the connection already exists
```suggestion
```

2022-04-12 00:11 UTC, bgeltz commented on service/geopmdpy/service.py
> +            # the initial reference count of 1.
```suggestion
```

2022-04-12 00:11 UTC, bgeltz commented on service/geopmdpy/service.py
> +        # is enforced by the _session_schema.
```suggestion
```

2022-04-12 00:11 UTC, bgeltz commented on service/geopmdpy/service.py
> +            # zero reference count.
```suggestion
            # The daemon died, restarted, and found a session with
            # zero reference count.
```

2022-04-12 00:11 UTC, bgeltz commented on service/geopmdpy/service.py
> +            # last reference, close the session completely
```suggestion
```

2022-04-12 00:11 UTC, bgeltz commented on service/geopmdpy/service.py
> +            # more than one reference, decrement the reference count
```suggestion
```

2022-04-12 00:36 UTC, bgeltz approved these changes

2022-04-12 00:42 UTC, merged