Edit the `trace_signals()` and `report_signals()` in Environment
geopm/geopm pull request #2278
Opened 2022-04-20 17:06 UTC by Krebrov001

- Modify these methods to use a common internal `signal_parser_method()`
- Modify the Reporter and Tracer classes where these methods are used.
- Move the common code into the `signal_parser_method()`

- Relates to #2052
- Fixes #2052

2022-04-20 17:41 UTC, cmcantalupo commented on src/Environment.hpp
> +            virtual std::vector<std::pair<std::string, int> > signal_parser(std::string environment_variable_contents) const = 0;
signal_parser belongs in EnvironmentImp, not in the public interface of Environment.

2022-05-05 23:30 UTC, cmcantalupo commented on service/src/geopm/PlatformIO.hpp
> +            virtual bool signal_exists(const std::string &signal_name) const = 0;
Although in principle this interface seems useful, we cannot simply append to the PlatformIO C++ interface.  This interface is exposed in C, Python, and through DBus in addition to the C++ implementation.  To add such a public interface to PlatformIO would require wrappers for all these other APIs.  

In addition, the implementation for this method is easily accomplished with an existing PlatformIO interface in all supported languages with something like:

```
    auto signal_names = platform_io().signal_names();
    bool signal_exists = (signal_names.find(signal_name) != signal_names.end());
```

similar code can be used for controls and the `control_names()` method.  I'm not in favor of adding an interface which contains logic that can be easily derived from another interface.

2022-05-05 23:34 UTC, cmcantalupo commented on src/Environment.cpp
> +                                   const PlatformIO* platform_io)
```suggestion
                                   const PlatformIO *platform_io)
```

2022-05-05 23:39 UTC, cmcantalupo commented on src/Environment.cpp
> +            if (!m_platform_io->signal_exists(signal_domain[0])) {
```suggestion

        auto signals_avail = m_platform_io->signal_names();
        auto individual_signals = geopm::string_split(environment_variable_contents, ",");
        for (const auto& signal : individual_signals) {
            auto signal_domain = geopm::string_split(signal, "@");
            if (signals_avail.find(signal_domain[0]) == signals_avail.end()) {
```

2022-05-05 23:43 UTC, cmcantalupo commented on src/Reporter.cpp
> +            } else {
```suggestion
            }
            else {
```

2022-05-05 23:46 UTC, cmcantalupo requested changes, later dismissed
Please remove signal_exists() from public PlatformIO interface.  Otherwise looks pretty good.

2022-05-09 18:20 UTC, bgeltz requested changes

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +    actual_signals = ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents);
```suggestion
    actual_signals = m_env->signal_parser(environment_variable_contents);
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +    actual_signals = ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents);
```suggestion
    actual_signals = m_env->signal_parser(environment_variable_contents);
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +        ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents),
```suggestion
        m_env->signal_parser(environment_variable_contents),
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +        (std::string("PlatformTopo::domain_name_to_type(): unrecognized domain_name: ") + std::string("invalid"))
```suggestion
        "PlatformTopo::domain_name_to_type(): unrecognized domain_name: invalid")
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +        ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents),
```suggestion
        m_env->signal_parser(environment_variable_contents),
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +        (std::string("EnvironmentImp::signal_parser(): Environment trace extension contains signals with multiple \"@\" characters."))
```suggestion
        "EnvironmentImp::signal_parser(): Environment trace extension contains signals with multiple \"@\" characters.")
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +        ((EnvironmentImp*)m_env.get())->signal_parser(environment_variable_contents),
```suggestion
        m_env->signal_parser(environment_variable_contents),
```

2022-05-09 18:20 UTC, bgeltz commented on test/EnvironmentTest.cpp
> +        (std::string("Invalid signal : ").append("NUM_VACUUM_TUBES"))
```suggestion
        "Invalid signal : NUM_VACUUM_TUBES")
```

2022-05-10 05:52 UTC, Krebrov001 commented
@bgeltz can you please look at this?

2022-05-10 17:04 UTC, bgeltz approved these changes

2022-05-10 17:38 UTC, cmcantalupo approved these changes

2022-05-10 17:38 UTC, merged