Rename all occurences of "accelerator" into "gpu"
geopm/geopm pull request #2302
Opened 2022-05-06 17:12 UTC by Krebrov001

- Relates to #2171 
- Fixes #2172 

Rename all occurences of "accelerator" into "gpu" within files in the `MANIFEST`.
Also rename the actual files themselves:

```
service/src/AcceleratorTopo.cpp
service/src/AcceleratorTopo.hpp
service/src/AcceleratorTopoNull.cpp
service/src/AcceleratorTopoNull.hpp
service/src/LevelZeroAcceleratorTopo.cpp
service/src/LevelZeroAcceleratorTopo.hpp
service/src/NVMLAcceleratorTopo.cpp
service/src/NVMLAcceleratorTopo.hpp
service/test/AcceleratorTopoNullTest.cpp
service/test/LevelZeroAcceleratorTopoTest.cpp
service/test/MockAcceleratorTopo.hpp
service/test/NVMLAcceleratorTopoTest.cpp
```

2022-05-06 23:14 UTC, cmcantalupo commented
accelerator -> gpu
Accelerator -> GPU
ACCELERATOR -> GPU

2022-05-09 16:29 UTC, lhlawson commented
```
[hpe-sx40:~] geopmread GPU_ENERGY board 0
1203543656.393
[hpe-sx40:~] geopmread GPU_ENERGY board 0
1203543905.611
[hpe-sx40:~] geopmread GPU_POWER board 0
177.005
[hpe-sx40:~] geopmread GPU_POWER gpu 0
Error: cannot read signal: <geopm> Invalid argument: PlatformTopo::domain_name_to_type(): unrecognized domain_name: gpu: at src/PlatformTopo.cpp:453
[hpe-sx40:~] geopmread GPU_POWER board_gpu 0
45.715
[hpe-sx40:~] geopmread GPU_POWER board_accelerator 0
Error: cannot read signal: <geopm> Invalid argument: PlatformTopo::domain_name_to_type(): unrecognized domain_name: 
[hpe-sx40:~] geopmread GPU_FREQUENCY_STATUS board_gpu 0
135000000
[hpe-sx40:~] geopmwrite GPU_FREQUENCY_CONTROL board_gpu 0 1530000000
[hpe-sx40:~] geopmread GPU_FREQUENCY_STATUS board_gpu 0
1530000000          
```
Live system testing above.  Not tested: 
- non-root privileges 
- all GPUs, beyond testing of board level readings
- dynamic monitoring/control with a gpu enabled agent (monitor of GPU signals, GPU-CA, etc) 
- accuracy of readings, beyond visual inspection vs previous readings on the same system.

2022-05-09 22:37 UTC, Krebrov001 commented
Please review
@cmcantalupo @bgeltz  @lhlawson

2022-05-09 23:39 UTC, Krebrov001 commented
I removed the `rename_accelerator.py` from this branch/pull request `issue-2171`.

It is now located on the branch `rename_script`.

2022-05-09 23:40 UTC, bgeltz requested changes
We should be consistent about when GPU is capitalized in comments and error strings.  When it's used in a sentence or similar, it should always be GPU or GPUs.

I marked many of these, but I did not mark them all.  There are many more that need to be corrected.

2022-05-09 23:40 UTC, bgeltz commented on service/docs/source/security.rst
> +control Intel gpu devices. These signals and controls include
```suggestion
control Intel GPU devices. These signals and controls include
```

2022-05-09 23:40 UTC, bgeltz commented on service/configure.ac
> +  [AS_HELP_STRING([--enable-nvml], [Enables use of the NVML library to support NVML board gpus])],
```suggestion
  [AS_HELP_STRING([--enable-nvml], [Enables use of the NVML library to support NVML board GPUs])],
```

2022-05-09 23:40 UTC, bgeltz commented on service/configure.ac
> +  [AS_HELP_STRING([--enable-dcgm], [Enables use of the DCGM library to support NVIDIA board gpus])],
```suggestion
  [AS_HELP_STRING([--enable-dcgm], [Enables use of the DCGM library to support NVIDIA board GPUs])],
```

2022-05-09 23:40 UTC, bgeltz commented on service/configure.ac
> +  AC_DEFINE([GEOPM_ENABLE_DCGM], [ ], [Enables use of the DCGM library to support NVIDA board gpus])
```suggestion
  AC_DEFINE([GEOPM_ENABLE_DCGM], [ ], [Enables use of the DCGM library to support NVIDA board GPUs])
```

2022-05-09 23:40 UTC, bgeltz commented on service/configure.ac
> +  AC_DEFINE([GEOPM_ENABLE_NVML], [ ], [Enables use of the NVML library to support NVML board gpus])
```suggestion
  AC_DEFINE([GEOPM_ENABLE_NVML], [ ], [Enables use of the NVML library to support NVML board GPUs])
```

2022-05-09 23:40 UTC, bgeltz commented on service/configure.ac
> +        AC_DEFINE([GEOPM_ENABLE_LEVELZERO], [ ], [Enables use of the levelzero library to support levelzero board gpus])
```suggestion
        AC_DEFINE([GEOPM_ENABLE_LEVELZERO], [ ], [Enables use of the levelzero library to support levelzero board GPUs])
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/DCGMDevicePool.hpp
> +            /// @brief Number of gpus that support DCGM on the platform.
```suggestion
            /// @brief Number of GPUs that support DCGM on the platform.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/DCGMDevicePool.hpp
> +            ///        gpu.
```suggestion
            ///        GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/DCGMDevicePool.hpp
> +            /// @brief Query DCGM for the latest value for an gpu.
```suggestion
            /// @brief Query DCGM for the latest value for an GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/DCGMDevicePool.hpp
> +            ///        gpu.
```suggestion
            ///        GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/GPUTopo.hpp
> +            /// @brief Number of gpus on the platform.
```suggestion
            /// @brief Number of GPUs on the platform.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/GPUTopo.hpp
> +            /// @brief CPU Affinitization set for a particular gpu
```suggestion
            /// @brief CPU Affinitization set for a particular GPU
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/GPUTopo.hpp
> +            ///        gpu
```suggestion
            ///        GPU
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.cpp
> +        //  Right now that is only gpus
```suggestion
        //  TODO: this should be expanded to return all supported GPU types.
        //  Right now that is only GPUs
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.cpp
> +        //  Right now that is only gpus
```suggestion
        //  TODO: this should be expanded to return all supported GPU types.
        //  Right now that is only GPUs
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            /// @return Number of LevelZero gpus.
```suggestion
            /// @brief Number of GPUs on the platform.
            /// @return Number of LevelZero GPUs.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            /// @brief Number of gpus on the platform.
```suggestion
            /// @brief Number of GPUs on the platform.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            /// @return Number of LevelZero gpus or gpu chips.
```suggestion
            /// @return Number of LevelZero GPUs or GPU chips.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        domain of the gpu.
```suggestion
            ///        domain of the GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        domain of the gpu.
```suggestion
            ///        domain of the GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        domain of the gpu.
```suggestion
            ///        domain of the GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        domain of the gpu.
```suggestion
            ///        domain of the GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        domain of the gpu.
```suggestion
            ///        domain of the GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        domain of the gpu.
```suggestion
            ///        domain of the GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-09 23:40 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            ///        Level Zero gpu.
```suggestion
            ///        Level Zero GPU.
```

2022-05-10 17:40 UTC, bgeltz approved these changes

2022-05-10 17:49 UTC, cmcantalupo approved these changes

2022-05-10 17:49 UTC, merged