Reorganize man pages to create chapter 7 pages for the GEOPM PIO interface
geopm/geopm pull request #2329
Opened 2022-05-20 21:29 UTC by cmcantalupo

- Includes Asma's work to add an SST man page for chapter 7
- Fixes #2314

2022-05-21 00:31 UTC, bgeltz commented on service/docs/source/conf.py
> +    "geopm_pio_sst.7",
Missing geopm_pio.7.rst

2022-05-21 00:31 UTC, bgeltz commented on service/docs/source/geopm.7.rst
> +`geopm_pio_sst(7) <geopm_pio_sst.7.html>`_\ ,
Mission pio.7.rst

2022-05-23 19:02 UTC, dannosliwcd requested changes

2022-05-23 19:02 UTC, dannosliwcd commented on service/docs/source/geopm_pio_sst.7.rst
> +* ``SST::COREPRIORITY:n:WEIGHT``:
#2332 went in today to rename this to `SST::COREPRIORITY:n:PRIORITY` and scale it to the `[0,1]` range. The ordering is preserved in that change (so 0 is still assigned to the bucket that should get more budget).

2022-05-24 19:11 UTC, lhlawson commented
Added GPU IO documentation from #2327.

2022-05-24 21:43 UTC, cmcantalupo commented on service/docs/source/geopm_pio_levelzero.7.rst
> +.. role:: raw-html-m2r(raw)
please remove

2022-05-24 21:53 UTC, lhlawson commented on service/docs/source/geopm_pio_nvml.7.rst
> +  *  ``Domain``: gpu
Capitalize consistently (i.e. Average and GPU or average or gpu)

2022-05-24 22:12 UTC, dannosliwcd commented
Notes from a discussion about this:

How to resolve the redundancy issue, where controls will have duplicate documentation for their same-named signals:
-	have a section for all signals
-	have a section for all controls. Add a note that all controls can also be read.

Include info about when/where signals and controls appear to a user. E.g., GEOPM must be compiled with support for this feature, must be on hardware that supports it.

**TODO** in general: Remove m2r comments and annotations (e.g., “role” headers, or any strings that say “m2r”, backticks followed by backslash and space in our lists of definitions “`\ :” the backslash space is unnecessary)

2022-05-25 19:01 UTC, dannosliwcd commented on service/docs/source/geopm_pio_sst.7.rst
> +steps are also in the ``SSTFrequencyGovernor``.
Probably shouldn't refer to that class in docs yet.

`SSTFrequencyGovernor` isn't targeted until 2.1. I'm also looking into whether I can take care of that in `FrequencyGovernor` instead.

2022-05-26 20:21 UTC, dannosliwcd commented on service/docs/source/geopm_pio.7.rst
> +`geopm::PlatformTopo(3) <GEOPM_CXX_MAN_PlatformTopo.3.html>`_.  A
Some of the readers of man 7 geopm_pio may be end-users trying to understand which signals/controls they are interested in. Should this also mention `geopmread --domain`?

2022-05-31 15:32 UTC, dannosliwcd requested changes, later dismissed
The `--geopm-record-filter` description in `geopmlaunch(1)` seems very long. See if we can shorten it a bit without hurting its usefulness, and offload some of the discussion to `geopm_pio_profile(7)`. That section-7 page should cover the EPOCH_COUNT, REGION_HASH, and other singals provided by the profile iogroup, so find a way to relate EPOCH_COUNT and REGION_HASH to the record filter.

Also specific questions related to that geopmlaunch option:

> The first parameter is the buffer size; the default if not provided is 100. The second parameter is the minimum stable period length in number of records. The third parameter is the stable period hysteresis factor. The fourth parameter is the unstable period hysteresis factor."

> 
> what is a buffer size?  is that in number of samples, bytes, seconds?

> 
> "stable period hysteresis factor"
?

> how is that normalized

2022-05-31 17:07 UTC, asmaalrawi submitted a review, later dismissed

2022-05-31 21:41 UTC, dannosliwcd commented on service/docs/source/geopm_pio.7.rst
> +
Remove

2022-05-31 21:42 UTC, dannosliwcd commented on service/docs/source/geopm_pio.7.rst
> +
Remove

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +To use the GEOPM LevelZero signals and controls GEOPM must be compiled against the oneAPI LevelZero libraries and must be run on a system with discrete GPUs supported by LevelZero.  In addition the u
I think it would be useful to explain how to compile GEOPM with L0 support via the ```--enable-levelzero``` configure time option.  If we have other docu about how configure works, a pointer here would be good.

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    Average GPU power over 40ms (via geopmread) or 8 control loop iterations.  Derivative signal based on LEVELZERO::GPU_ENERGY
```suggestion
    Average GPU power over 40ms (via ``geopmread``) or 8 control loop iterations.  Derivative signal based on ``LEVELZERO::GPU_ENERGY``
```

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    The current frequency of the GPU Compute Hardware
```suggestion
    The current frequency of the GPU Compute Hardware.
```

All of these descriptions should end with a period.  It looks like there are several spots in this IOGroup that have the trailing period absent.  This should also be reflected in the string that is presented with ``geopmread``.

We were doing this originally in i.e. the MSRIOGroup, but it seems recently added signals/controls also have the period missing there.  They should all be updated appropriately.

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +
```suggestion


```
Is this supposed to be 2 \n's?  I've got opens on the style we want here so let's bring it up with the group.

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +``LEVELZERO::GPU_UNCORE_UTILIZATION``
```suggestion
``LEVELZERO::GPU_UNCORE_ACTIVITY``
```
This seems to be what we settled on during the arch meeting.

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +To use the GEOPM LevelZero signals and controls GEOPM must be compiled against the oneAPI LevelZero libraries and must be run on a system with discrete GPUs supported by LevelZero.  In addition the u
I think it would be useful to expand the bit about ``ZES_ENABLE_SYSMAN=1`` to show an example invocation in a ```.. code-block::``` section.  I would show the 2 different ways of doing this: via a single command that begins with setting the variable and separately via 2 commands with the first being the export and the second being ```geopmlaunch``` or similar.

2022-06-01 00:01 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +`geopmread(1) <geopmread.1.html>`_
```suggestion
`geopm(7) <geopm.7.html>`_,
`geopm_pio(7) <geopm_pio.7.html>`_,
`geopm::IOGroup(3) <GEOPM_CXX_MAN_IOGroup.3.html>`_,
`geopmwrite(1) <geopmwrite.1.html>`_,
`geopmread(1) <geopmread.1.html>`_
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +To use the GEOPM NVML signals and controls GEOPM must be compiled against the NVML libraries and must be run on a system with hardware supported by NVML.
Same comment here as with the L0 docu: we should spell out what it means to "compile GEOPM against NVML" for the configure time options and pointers to other relevant build time docu.

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +    GPU energy consumptoin in joules since the driver was loaded
```suggestion
    GPU energy consumption in joules since the driver was loaded.
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +    GPU Power usage in watts
```suggestion
    GPU power usage in watts.
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +See Also
Include a pointer to NVML documentation.  Many of the descriptions above allude to this.

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +      *  ``Unit``: None
Pointer here to the NVML docu regarding this signal?

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +    GPU PCIE receive throughput in Bytes per Second over a 20 millisecond period
```suggestion
    GPU PCIE receive throughput in bytes per second over a 20 millisecond period.
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +    GPU PCIE transmit throughput in Bytes per Second over a 20 millisecond period
```suggestion
    GPU PCIE transmit throughput in bytes per second over a 20 millisecond period.
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +    GPU associated with the specified cpu as determined by querying active processes on the GPU.  If no GPUs map to the CPU -1 is returned.  If multiple GPU map to the CPU NAN is returned.
```suggestion
    GPU associated with the specified CPU as determined by querying active processes on the GPU.  If no GPUs map to the CPU -1 is returned.  If multiple GPU map to the CPU NAN is returned.
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +Signal Aliases
This section needs to have its style aligned with other similar sections.  E.g. replace "aliases" with "maps", and put it all on a single line.  This also needs to be done for the L0 page.  We should hash out how we want this to look and then apply it to all the pages.

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_nvml.7.rst
> +~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_sst.7.rst
> +~~~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~~~~
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_dcgm.7.rst
> +To use the GEOPM DCGM signals and controls GEOPM must be compiled against the DCGM libraries and must be run on a system with hardware supported by DCGM.
Include the information about the relevant configure time flag.

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_dcgm.7.rst
> +~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~
```

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_dcgm.7.rst
> +~~~~~~~~~~~~~~~~
This section needs to be style aligned with the other pages.

2022-06-01 00:35 UTC, bgeltz commented on service/docs/source/geopm_pio_cnl.7.rst
> +Signal Aliases
We need to decide the ordering of these sections.  Here, you've got the aliases at the end, just before the "See Also" section.

Lowren has the aliases follow the normal sections, i.e. Signals -> Signal Aliases -> Controls -> Control Aliases -> See Also.

2022-06-01 12:08 UTC, dannosliwcd commented on service/docs/source/geopm_pio.7.rst
> +``geopm_domain_e`` enum and the hierarchical platform description see
The linked page doesn't provide that information, but says to see `geopm_topo_c(3)` for information about `geopm_domain_e`

2022-06-01 12:10 UTC, dannosliwcd commented on service/docs/source/geopm_topo_c.3.rst
>  The ``geopm_domain_e`` enum defines a set of values that correspond to
This list is missing `GEOPM_DOMAIN_GPU_CHIP`.

2022-06-01 14:58 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +To use the GEOPM LevelZero signals and controls GEOPM must be compiled against the oneAPI LevelZero libraries and must be run on a system with discrete GPUs supported by LevelZero.  In addition the u
Agreed on both.  @cmcantalupo we removed the configure option since this was intended to be 'user' documentation.  Where are we putting 'developer' documentation?

2022-06-01 15:05 UTC, lhlawson commented on service/docs/source/geopm_pio.7.rst
> +    Average GPU temperature in degrees Celsius.
https://spec.oneapi.io/level-zero/latest/sysman/api.html#zes-temp-sensors-t
LevelZero exposes the maximum temperature across the device domain, or the minimum, but not the average.
https://spec.oneapi.io/level-zero/latest/sysman/api.html#zestemperaturegetstate

2022-06-01 17:08 UTC, lhlawson commented on service/docs/source/geopm_pio.7.rst
> +    Average GPU temperature in degrees Celsius.
Our LevelZero IO Group also does not currently expose a signal for this alias.

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~~~
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``CYCLES_REFERENCE``
```suggestion
``CPU_CYCLES_REFERENCE``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``CYCLES_THREAD``
```suggestion
``CPU_CYCLES_THREAD``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``ENERGY_DRAM``
```suggestion
``DRAM_ENERGY``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``ENERGY_PACKAGE``
```suggestion
``PACKAGE_ENERGY``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``INSTRUCTIONS_RETIRED``
```suggestion
``CPU_INSTRUCTIONS_RETIRED``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_LIMIT``
```suggestion
``CPU_POWER_PACKAGE_LIMIT``
```
or
```suggestion
``CPU_PACKAGE_POWER_LIMIT``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_MAX``
```suggestion
``CPU_POWER_PACKAGE_MAX``
```
or
```suggestion
``CPU_PACKAGE_POWER_MAX``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_MIN``
```suggestion
``CPU_POWER_PACKAGE_MIN``
```
or
```suggestion
``CPU_PACKAGE_POWER_MIN``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_TDP``
```suggestion
``CPU_POWER_PACKAGE_TDP``
```
or
```suggestion
``CPU_PACKAGE_POWER_TDP``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_TIME_WINDOW``
```suggestion
``CPU_POWER_PACKAGE_TIME_WINDOW``
```
or
```suggestion
``CPU_PACKAGE_POWER_TIME_WINDOW``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``TIMESTAMP_COUNTER``
```suggestion
``CPU_TIMESTAMP_COUNTER``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_LIMIT``
```suggestion
``CPU_POWER_PACKAGE_LIMIT``
```
or
```suggestion
``CPU_PACKAGE_POWER_LIMIT``
```

2022-06-01 17:14 UTC, bgeltz commented on service/docs/source/geopm_pio_msr.7.rst
> +``POWER_PACKAGE_TIME_WINDOW``
```suggestion
``CPU_POWER_PACKAGE_TIME_WINDOW``
```
or
```suggestion
``CPU_PACKAGE_POWER_TIME_WINDOW``
```

2022-06-01 18:26 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    The last frequency request for the GPU Compute Hardware
Include info about setting this, and what the expectations are around reading, NaNs, etc.

2022-06-01 18:26 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    The maximum supported power limit in Watts
Max supported by what?  Hardware?  Software?  Is this a theoretical limit?

2022-06-01 18:26 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    Default power limit of the GPU in Watts
Is this the boot time value?  Or just the value if it's never been set?  Or both?

2022-06-01 18:26 UTC, bgeltz commented on service/docs/source/geopm_pio_levelzero.7.rst
> +To use the GEOPM LevelZero signals and controls GEOPM must be compiled against the oneAPI LevelZero libraries and must be run on a system with discrete GPUs supported by LevelZero.  In addition the u
Add a tooltip box that spells out how to do this configure time enabling, with an explanation that a future release of GEOPM will have this enabled in an RPM so you do not have to do a source build.

2022-06-02 15:14 UTC, dannosliwcd commented
A lot of the section 3 man pages have malformed function argument names. It looks like it's the names that have underscores in them.

e.g., `_signal\ *name*` should probably be `*signal_name*`

2022-06-06 17:53 UTC, lhlawson commented on service/docs/source/geopm_pio.7.rst
> +    Average GPU temperature in degrees Celsius.
```suggestion
    GPU temperature in degrees Celsius.
```

2022-06-07 19:45 UTC, Krebrov001 requested changes

2022-06-07 19:45 UTC, Krebrov001 commented on service/docs/source/geopm_pio.7.rst
> +
There are two of them.

2022-06-07 23:06 UTC, Krebrov001 commented on service/docs/source/geopm_pio.7.rst
> +
Keep the second one.

2022-06-10 22:06 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +``LEVELZERO::GPU_UNCORE_UTILIZATION``
I agree that GPU_UNCORE_ACTIVITY is the high level alias, but this is meant to represent the lower level Sysman 'engine activity utilization' counter https://spec.oneapi.io/level-zero/latest/sysman/api.html#_CPPv418zes_engine_stats_t.  

Is it worthwhile to keep this named as is and just alias it to GPU_UNCORE_ACTIVITY (similar to the DCGM::DRAM_ACTIVE being aliased to GPU_UNCORE_ACTIVITY)?

2022-06-13 21:06 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +To use the GEOPM LevelZero signals and controls GEOPM must be compiled against the oneAPI LevelZero libraries and must be run on a system with discrete GPUs supported by LevelZero.  To compile agains
```suggestion
To use the GEOPM LevelZero signals and controls GEOPM must be compiled against the oneAPI LevelZero libraries and must be run on a system with discrete GPUs supported by LevelZero.  To compile against the oneAPI LevelZero libraries geopm must be configured using the --enable-levelzero flag.  The optional --with-levelzero flag may be used to indicate the path of the required libraries.  In addition the user must export ZES_ENABLE_SYSMAN=1 as specified by the Intel oneAPI Level Zero Sysman documentation.  See the Sysman specification for more info on related environment variables and their usage.
```

2022-06-13 21:07 UTC, lhlawson commented on service/docs/source/geopm_pio_nvml.7.rst
> +To use the GEOPM NVML signals and controls GEOPM must be compiled against the NVML libraries and must be run on a system with hardware supported by NVML.  To compile against the NVML libraries geopm
```suggestion
To use the GEOPM NVML signals and controls GEOPM must be compiled against the NVML libraries and must be run on a system with hardware supported by NVML.  To compile against the NVML libraries geopm must be configured using the --enable-nvml flag.  The optional --with-nvml flag may be used to indicate the path of the required libraries.
```

2022-06-13 21:07 UTC, lhlawson commented on service/docs/source/geopm_pio_dcgm.7.rst
> +To use the GEOPM DCGM signals and controls GEOPM must be compiled against the DCGM libraries and must be run on a system with hardware supported by DCGM.To compile against the oneAPI LevelZero librar
```suggestion
To use the GEOPM DCGM signals and controls GEOPM must be compiled against the DCGM libraries and must be run on a system with hardware supported by DCGM.To compile against the oneAPI LevelZero libraries geopm must be configured using both the --enable-nvml flag and the --enable-dcgm flag.  The optional --with-dcgm flag may be used to indicate the path of the required libraries.
```

2022-06-14 21:28 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    Timestamp for the GPU energy read in seconds.
```suggestion
    Timestamp for the GPU energy read in seconds.  Value is cached on LEVELZERO::ENERGY read.
```

2022-06-21 15:39 UTC, dannosliwcd commented on service/docs/source/geopm_pio.7.rst
> +`geopm::PlatformTopo(3) <GEOPM_CXX_MAN_PlatformTopo.3.html>`_.  A
Added a suggestion to see geopmread/write for CLI-based exploration of PlatformIO

2022-06-21 16:04 UTC, dannosliwcd commented
I combed through my stale comments on this PR. One that partially remains is the out-of-order words with underscores. (https://github.com/geopm/geopm/pull/2329#issuecomment-1144983682)

`grep '_\w\+\\ \*' docs/source/*rst` at least catches some remaining instances of that problem in `geopmbench.1`, `GEOPM_CXX_MAN_MSRIOGroup.3` and `GEOPM_CXX_MAN_SampleAggregator.3`

2022-06-21 18:47 UTC, lhlawson commented on integration/test_skipped/test_levelzero_signals.py
> +        frequency_gpu = geopm_test_launcher.geopmread("LEVELZERO::GPU_CORE_FREQUENCY gpu 0")
Should be GPU_CORE_FREQUENCY_STATUS

2022-06-21 18:48 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    Maps to ``LEVELZERO::ENERGY``.
```suggestion
    Maps to ``LEVELZERO::GPU_ENERGY``.
```

2022-06-21 18:49 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +``LEVELZERO::ENERGY_TIMESTAMP``
```suggestion
``LEVELZERO::GPU_ENERGY_TIMESTAMP``
```

2022-06-21 18:49 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +``LEVELZERO::ENERGY``
```suggestion
``LEVELZERO::GPU_ENERGY``
```

2022-06-21 18:49 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    average GPU power over 40ms (via geopmread) or 8 control loop iterations.  Derivative signal based on ``LEVELZERO::ENERGY``.
```suggestion
    average GPU power over 40ms (via geopmread) or 8 control loop iterations.  Derivative signal based on ``LEVELZERO::GPU_ENERGY``.
```

2022-06-21 19:44 UTC, bgeltz submitted a review, later dismissed

2022-06-21 19:47 UTC, Krebrov001 submitted a review, later dismissed

2022-06-21 20:00 UTC, bgeltz approved these changes

2022-06-21 20:11 UTC, merged