Added Level Zero Throttle Reasons signal
geopm/geopm pull request #2369
Opened 2022-06-03 15:22 UTC by lhlawson

Signed-off-by: lhlawson <lowren.h.lawson@intel.com>

- Relates to #2638 feature request from github issues
- Fixes #2638 change request from github issues.

Provides GPU core domain throttle reasons as a LevelZeroIOGroup signal at a per chip level as covered in the Level Zero Sysman API - https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#frequency

Future PRs for percentage of time throttled should be considered.

2022-06-14 00:38 UTC, lhlawson commented on service/src/LevelZeroIOGroup.cpp
> +                                  Agg::average,
A bitwise OR makes more sense here for aggregation as it would represent all the throttling across the device compute domains

2022-07-14 21:14 UTC, cmcantalupo commented on service/src/LevelZeroDevicePool.cpp
> +                            " is not supported for the frequency domain.",
```suggestion
                            " is not supported for reading the \"frequency throttle reason\"",
```

2022-07-14 21:16 UTC, cmcantalupo commented on service/src/LevelZeroDevicePool.cpp
> +                            " is not supported for the frequency domain.",
Perhaps something more descriptive is possible, but "domain" was overused here.

2022-07-14 21:21 UTC, cmcantalupo commented on service/src/Agg.cpp
> +            for (auto it : filtered) {
```suggestion
            for (const auto &it : filtered) {
```

2022-07-14 21:38 UTC, cmcantalupo commented on service/src/geopm/Agg.hpp
> +            /// @brief Returns the output of bitwise OR over all the
The fact that the double is cast to a uint64_t before the bit comparison is not documented here.  I'm a little confused about what the user would expect if they passed a bit-field MSR here (one that ends in #).  In that case, it would be surprising that the cast is done, since the double precision representation of the register is not intended to be interpreted as a number.  I think this should be somehow identified in the name, perhaps: ``uint64_bitwise_or()``?

A double precision number cannot represent the bit reserved for the sign-bit in a int64_t as an integer value (the mantissa has fewer than 64 bits).  For this reason it is also a little surprising that the unsigned cast is done.  Why not just cast to a int64_t, or a long?  There is no logical difference here.

Perhaps we can have:
```
// Do a bitwise-or of the memory representing the double, this useful for bit field MSRs that end in #.
field_bitswise_or()
// Cast the double to a int64_t and then do bitwise-or.
integer_bitwise_or()
```

2022-07-14 21:38 UTC, cmcantalupo commented on service/test/AggTest.cpp
> +    EXPECT_EQ(0, Agg::bitwise_or({-1, 0}));
Surprising really....

2022-07-14 21:41 UTC, cmcantalupo requested changes
See comment about adding another aggregator.  The unsigned cast is a little confusing.

2022-07-14 22:05 UTC, cmcantalupo commented on service/src/Agg.cpp
> +                if (it >= 0) {
Lets not support -1 as a special value in the this implementation, rather do it on the LevelZeroIOGroup side.

2022-07-14 22:09 UTC, cmcantalupo commented on service/src/Agg.cpp
> +    double Agg::bitwise_or(const std::vector<double> &operand)
Needs to be mapped to a string and an enum in the bottom of the Agg.cpp imp.

2022-07-14 23:45 UTC, lhlawson commented on service/src/geopm/Agg.hpp
> +            /// @brief Returns the output of bitwise OR over all the
Updated to be integer_bitwise_or(), issue #2454 filed to track feature request for field_bitwise_or() and identify signals that may use it by default (such as raw MSRs).

2022-07-15 22:33 UTC, cmcantalupo approved these changes

2022-07-15 22:33 UTC, merged