Add support for `EVENT_SHORT_REGION`
geopm/geopm pull request #2433
Opened 2022-07-08 08:20 UTC by Krebrov001

- Relates to #1766

2022-07-08 15:38 UTC, lhlawson commented on src/ProfileTracer.cpp
> +                    result = string_format_integer(value);
```suggestion
                    result = string_format_hex(value);
```
This should provide the hex value of region as it is written.  
We may want to add an EVENT_SHORT_REGION count (which would use the string_format_integer), but for #1766 only the region addition is needed.

2022-07-08 16:44 UTC, lhlawson commented
LGTM.  

We may want to run this against a series of workloads to see if we can hit the case called out in #1766 where an exception would occur.  PENNANT may exhibits short region behavior, and it is integrated into the experiment infrastructure.

2022-07-15 22:49 UTC, cmcantalupo commented on src/ProfileTracerImp.hpp
> +    // defintion of the static data member
Please move to ApplicationSampler.cpp

2022-07-15 22:57 UTC, cmcantalupo commented on test/ProfileTracerTest.cpp
> +     m_data.push_back({40, 0, geopm::EVENT_SHORT_REGION, 0xdeadbeef});
```suggestion
     m_data.push_back({40, 0, geopm::EVENT_SHORT_REGION, 88});
```
in general the event number will not match the region hash

2022-07-15 22:58 UTC, cmcantalupo commented on test/ProfileTracerTest.cpp
> +     m_data.push_back({41, 1, geopm::EVENT_EPOCH_COUNT, region_hash});
```suggestion
     m_data.push_back({41, 1, geopm::EVENT_EPOCH_COUNT, 1});
```
The epoch count event should reflect a number times the epoch event has occurred.

2022-07-15 22:59 UTC, cmcantalupo commented on test/ProfileTracerTest.cpp
> +    EXPECT_CALL(m_application_sampler, get_short_region(0xdeadbeef))
```suggestion
    EXPECT_CALL(m_application_sampler, get_short_region(88))
```

2022-07-15 22:59 UTC, cmcantalupo commented on test/ProfileTracerTest.cpp
> +        "41|1|EPOCH_COUNT|4200145110"
```suggestion
        "41|1|EPOCH_COUNT|1"
```

2022-07-15 23:00 UTC, cmcantalupo requested changes
Just a couple of minor comments.

Looks like some issue with clang 12:
```
 FAIL: test/gtest_links/ProfileTracerTest.construct_update_destruct
 ```
 showed up in CI

2022-07-19 18:16 UTC, cmcantalupo approved these changes

2022-07-19 18:32 UTC, merged