Support for LevelZero GPU CHIP temperatures
geopm/geopm pull request #2743
Opened 2022-11-30 20:19 UTC by lhlawson

- Relates to #2742 story from github issues
- Fixes #2741 change request from github issues.

Update to levelzero code to provide GPU_CHIP temperature information. 

This PR is rebased on #2739 for support on systems with newer clang compiler toolchains.  It is expected that PR will be merged prior to this PR.  

This PR will remain in draft until additional testing is added in the LevelZero Device Pool & IOGroup unit tests.

2022-12-01 21:57 UTC, bgeltz requested changes

2022-12-01 21:57 UTC, bgeltz commented on service/src/LevelZero.hpp
> +
```suggestion
```

2022-12-01 21:57 UTC, bgeltz commented on service/src/LevelZero.hpp
> +
```suggestion
```

2022-12-01 21:57 UTC, bgeltz commented on service/src/LevelZero.hpp
> +            virtual int temperature_domain_count(unsigned int l0_device_idx, int l0_domain) const = 0;
```suggestion
            /// @brief Get the number of LevelZero temperature domains
            /// @param [in] l0_device_idx The index indicating a particular
            ///        Level Zero GPU.
            /// @param [in] l0_domain The LevelZero domain type being targeted
            /// @return GPU temperature domain count.
            virtual int temperature_domain_count(unsigned int l0_device_idx, int l0_domain) const = 0;
```

2022-12-01 21:57 UTC, bgeltz commented on service/src/LevelZeroDevicePool.hpp
> +
```suggestion
```

2022-12-01 21:57 UTC, bgeltz commented on service/src/LevelZeroIOGroup.cpp
> +                                  Agg::average,
```suggestion
                                  Agg::max,
```
Does this matter in this case?
Perhaps if you issued ```geopmread GPU_CORE_TEMPERATURE_MAXIMUM board 0``` and you wanted to see the absolute maximum across all GPUs?  As it is, reading at the board domain would take the average of all the GPUs max and return that.

2022-12-01 21:57 UTC, bgeltz commented on service/src/LevelZeroIOGroup.cpp
> +                                  Agg::average,
```suggestion
                                  Agg::max,
```
Same question here.

2022-12-02 00:06 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    *  **Aggregation**: expect_same
```suggestion
    *  **Aggregation**: max
```

2022-12-02 00:06 UTC, lhlawson commented on service/docs/source/geopm_pio_levelzero.7.rst
> +    *  **Aggregation**: expect_same
```suggestion
    *  **Aggregation**: max
```

2022-12-08 21:46 UTC, bgeltz approved these changes

2022-12-08 21:49 UTC, bgeltz commented
LGTM, but I did notice that we're not consistent about initializing the ze_result_t variables.  There's one occurance of this in the constructor:
```
ze_result_t ze_result;
//Initialize
ze_result = zeInit(0);
```
But in all the other spots I saw, we declare ze_result_t's without initialization.  We might want to open an issue (or a bug depending on how you want to frame it) about properly initializing all of these.

2022-12-08 22:31 UTC, lhlawson commented
> LGTM, but I did notice that we're not consistent about initializing the ze_result_t variables. There's one occurance of this in the constructor:
> 
> ```
> ze_result_t ze_result;
> //Initialize
> ze_result = zeInit(0);
> ```
> 
> But in all the other spots I saw, we declare ze_result_t's without initialization. We might want to open an issue (or a bug depending on how you want to frame it) about properly initializing all of these.

https://github.com/geopm/geopm/issues/2757 filed to track the issue (if we're not tackling it in this PR)

2022-12-09 02:00 UTC, merged