Get GPU topo information from topo cache
geopm/geopm pull request #2842
Opened 2023-02-08 23:18 UTC by cmcantalupo

- Fixes #2800 change request from github issues.
- TODO: Still need to adjust unit tests

2023-02-09 00:07 UTC, bgeltz requested changes

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +            const GPUTopo &gtopo = gpu_topo();
```suggestion
            const GPUTopo &gtopo = geopm::gpu_topo();
```

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +            const GPUTopo &gtopo = gpu_topo();
Somewhere in here there should be a throw to see if ZE_AFFINITY_MASK is set.  It's unfortunate that it's a L0 specific env var.  Not sure if NVML has a similar feature.

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +                    GEOPM_DOMAIN_PACKAGE_INTEGRATED_GPU,
```suggestion
```

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +
```suggestion
```

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +        m_gpu_info[GEOPM_DOMAIN_PACKAGE_INTEGRATED_GPU] = parse_lscpu_gpu(lscpu_map, GEOPM_DOMAIN_PACKAGE_INTEGRATED_GPU);
```suggestion
```

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +              {GEOPM_DOMAIN_PACKAGE_INTEGRATED_GPU, {}},
```suggestion
```

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +                    cpu_set_it->insert(stoi(cpu_str));
```suggestion
                    cpu_set_it->insert(std::stoi(cpu_str));
```

2023-02-09 00:07 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +                for (const auto &cpu_str : string_split(lscpu_it->second, ",")) {
```suggestion
                for (const auto &cpu_str : geopm::string_split(lscpu_it->second, ",")) {
```

2023-02-09 16:04 UTC, cmcantalupo commented on service/src/PlatformTopo.cpp
> +            const GPUTopo &gtopo = gpu_topo();
I just put the check in the constructor for the LevelZeroGPUTopo.

2023-02-10 02:41 UTC, cmcantalupo commented on service/src/PlatformTopo.cpp
> +        if (getuid() == 0) {
geteuid()?

2023-02-10 02:42 UTC, cmcantalupo commented on service/src/PlatformTopo.cpp
> +            if (getuid() == 0) {
geteuid()?

2023-02-10 23:16 UTC, bgeltz requested changes

2023-02-10 23:16 UTC, bgeltz commented on service/src/PlatformTopo.cpp
> +
```suggestion
```

2023-02-10 23:17 UTC, bgeltz approved these changes

2023-02-10 23:50 UTC, merged