Added example code in C, C++ and python to do batch reads
geopm/geopm pull request #3139
Opened 2023-09-22 17:30 UTC by alawibaba

2023-09-22 17:56 UTC, bgeltz requested changes

2023-09-22 17:56 UTC, bgeltz commented on service/docs/source/overview.rst
> +                char name[1024];
```suggestion
                char name[NAME_MAX];
```

2023-09-22 19:56 UTC, cmcantalupo commented on service/docs/source/overview.rst
> +
```suggestion
            }
```

2023-09-22 21:31 UTC, cmcantalupo commented on service/docs/source/overview.rst
> +        }
```suggestion
            int time_idx, freq_idx, err;
            double time_value, freq_value;

            time_idx = geopm_pio_push_signal("TIME",
                                             GEOPM_DOMAIN_BOARD,
                                             0);
            if (time_idx < 0) {
                return time_idx;
            }
            freq_idx = geopm_pio_push_signal("CPU_FREQUENCY_STATUS",
                                             GEOPM_DOMAIN_PACKAGE,
                                             0);
            if (freq_idx < 0) {
                return freq_idx;
            }
            err = geopm_pio_read_batch();
            if (err < 0) {
                return err;
            }
            err = geopm_pio_sample(time_idx, &time_value);
            if (err < 0) {
                return err;
            }
            err = geopm_pio_sample(freq_idx, &freq_value);
            if (err < 0) {
                return err;
            }
            printf("Elapsed time = %f\n", time_value);
            printf("Current CPU frequency for core 0 = %f\n", freq_value);

            return 0;
        }

        int main (int argc, char** argv)
        {
            char err_msg[PATH_MAX];
            int err = read_signals();
            if (err < 0) {
                geopm_error_message(err, err_msg, PATH_MAX);
                fprintf(stderr, "Err msg = %s\n", err_msg);
            }

            return 0;
        }
```

2023-09-22 21:33 UTC, cmcantalupo commented on service/docs/source/overview.rst
> +                                       GEOPM_DOMAIN_PACKAGE, 0);
```suggestion
            time_idx = pio.push_signal("TIME",
                                       GEOPM_DOMAIN_BOARD, 0);
            freq_idx = pio.push_signal("CPU_FREQUENCY_STATUS",
                                       GEOPM_DOMAIN_PACKAGE, 0);
```

2023-09-22 22:49 UTC, cmcantalupo approved these changes, later dismissed

2023-09-23 00:45 UTC, bgeltz approved these changes

2023-09-23 00:46 UTC, cmcantalupo approved these changes

2023-09-23 01:05 UTC, merged