Fix issue with save/restore and writing in general
geopm/geopm pull request #3312
Opened 2024-01-09 20:27 UTC by cmcantalupo

- Fixes #3311

2024-01-09 20:29 UTC, dannosliwcd approved these changes, later dismissed

2024-01-09 21:50 UTC, dannosliwcd approved these changes, later dismissed

2024-01-09 22:50 UTC, bgeltz commented on service/src/SaveControl.cpp
> +            if (std::isfinite(ss.setting)) {
Why are we trying to restore NaNs?  That seems like the "real" bug.

2024-01-09 23:12 UTC, bgeltz requested changes

2024-01-09 23:12 UTC, bgeltz commented on service/src/SaveControl.cpp
> +            }
else emit warning to all the proper spots

2024-01-10 01:33 UTC, bgeltz submitted a review, later dismissed

2024-01-10 01:33 UTC, bgeltz commented on service/src/SysfsIOGroup.cpp
> +            throw Exception("SysfsIOroup::" + method_name + "(): Cannot write control setting which could not be read.",
```suggestion
            throw Exception("SysfsIOGroup::" + method_name + "(): Cannot write control setting which could not be read.",
```

2024-01-10 01:35 UTC, bgeltz approved these changes

2024-01-10 01:51 UTC, merged