Fedora packaging [WIP]
geopm/geopm pull request #3504
Opened 2024-06-05 00:03 UTC by cmcantalupo

WIP - THESE CHANGES ARE A WORK IN PROGRESS

Several changes will be required for fedora packaging

- Build from files committed to git only, do not download binaries
  - Do not build gtest or gmock, use packages
  - Do not download fuzz corpus unless fuzz testing is enabled
  - Create VERSION files in spec file rather than rely on generated versions in archive
- Run unit tests in %check sections

2024-06-06 23:46 UTC, cmcantalupo commented on geopmpy/geopmpy.spec.in
> +%setup
```suggestion
%setup -n geopm-%{version}
```

2024-06-21 18:12 UTC, bgeltz requested changes

2024-06-21 18:12 UTC, bgeltz commented on release/fedora/geopmdpy.spec
> +%py3_build
SETUPTOOLS_SCM_PRETEND_VERSION may help here
https://github.com/pypa/setuptools_scm/blob/main/docs/overrides.md

2024-06-21 18:12 UTC, bgeltz commented on libgeopmd/Makefile.am
> +	./make_rpm.sh
Double check that defining rpmbuild_flags with make rpm passes the flags through properly for things like levelzero enablement, etc.

A deprecation warning would also be nice.

2024-06-25 21:19 UTC, bgeltz requested changes

2024-06-25 21:19 UTC, bgeltz commented on geopmdpy/test/TestActiveSessions.py
> -                mock_get_session_path.called_once_with(contents['client_pid'])
A tech debt issue or similar should be filed about why this code path wasn't being hit.

2024-06-25 21:19 UTC, bgeltz commented on libgeopm/test/Makefile.mk
> +                         -lgtest \
If we're going to try to link against gtest and gmock when BUILD_GTEST is disabled, the documentation should be updated to reflect this new requirement.

2024-06-25 22:04 UTC, bgeltz approved these changes

2024-06-25 22:30 UTC, merged