Increase max open file descriptor limit
geopm/geopm pull request #3524
Opened 2024-06-24 18:42 UTC by sidjana

- Relates to #3523 bug report from github issues

[Brief description of the change]
The limit for maximum number of open file descriptors by the geopmd service has been increased to 16384 to support processors with large cpu count (> 256 cpus)

2024-06-25 18:56 UTC, cmcantalupo submitted a review, later dismissed

2024-06-25 22:21 UTC, cmcantalupo requested changes
Original syntax was correct see:
https://unix.stackexchange.com/questions/345595/how-to-set-ulimits-on-service-with-systemd

2024-07-03 20:00 UTC, dannosliwcd approved these changes

2024-07-08 15:29 UTC, cmcantalupo approved these changes

2024-07-08 15:29 UTC, merged