Set ZES_ENABLE_SYSMAN in enevironment prior to calling zeInit
geopm/geopm pull request #3616
Opened 2024-10-12 01:10 UTC by cmcantalupo

- Fixes #3539

2024-10-14 18:52 UTC, avilcheslopez approved these changes, later dismissed
Should the documentation (geopm_pio_levelzero(7)) be updated as well? Now that both paths (direct, through service) set it automatically, it seems the user no longer has to make sure it's set.

Also, with this change, does the service still need to set it (in libgeopmd/geopm.service)? If not, it might be a good idea to just set it in one place in case in the future we need to change that setting somehow.

2024-10-14 23:55 UTC, bgeltz approved these changes, later dismissed

2024-10-15 18:02 UTC, bgeltz requested changes
Re-jig to emit warnings instead of setenv calls.

This violates process expectations about setenv/getenv timing.

2024-10-15 22:20 UTC, cmcantalupo commented on libgeopmd/src/GPUTopo.cpp
> +            std::string(getenv("ZE_FLAT_DEVICE_HIERARCHY")) == "COMPOSITE") {
This is a behavior change.  Not 100% sure it is for the better...

2024-10-16 15:42 UTC, cmcantalupo commented on libgeopmd/src/LevelZero.cpp
> +                          << "                     rm -f /run/geopm/geopm-topo-cache; ZE_ENABLE_SYSMAN=1 ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE geopmread --cache\n";
Might be nice to only warn if we are actually creating a topo cache file, but plumbing that turns out to be a bit tricky.

2024-10-16 15:52 UTC, cmcantalupo commented
```
cmcantal@saruman:~/Git/geopm/libgeopmd (issue-3539)]$ ./geopmread > /dev/null
cmcantal@saruman:~/Git/geopm/libgeopmd (issue-3539)]$ sudo ./geopmread > /dev/null
Warning: <geopm> LevelZero features require the environment variable setting "ZE_ENABLE_SYSMAN=1".
                 LevelZero features require the environment variable setting "ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE".
                 This process may corrupt the topology cache file if LevelZero enabled GPUs are present.
                 Run the following commands to fix:
                     sudo rm -f /run/geopm/geopm-topo-cache
                     sudo env ZE_ENABLE_SYSMAN=1 ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE geopmread --cache

cmcantal@saruman:~/Git/geopm/libgeopmd (issue-3539)]$ sudo env ZE_ENABLE_SYSMAN=1 ./geopmread > /dev/null
Warning: <geopm> LevelZero features require the environment variable setting "ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE".
                 This process may corrupt the topology cache file if LevelZero enabled GPUs are present.
                 Run the following commands to fix:
                     sudo rm -f /run/geopm/geopm-topo-cache
                     sudo env ZE_ENABLE_SYSMAN=1 ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE geopmread --cache
cmcantal@saruman:~/Git/geopm/libgeopmd (issue-3539)]$ sudo env ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE  ./geopmread > /dev/null
Warning: <geopm> LevelZero features require the environment variable setting "ZE_ENABLE_SYSMAN=1".
                 This process may corrupt the topology cache file if LevelZero enabled GPUs are present.
                 Run the following commands to fix:
                     sudo rm -f /run/geopm/geopm-topo-cache
                     sudo env ZE_ENABLE_SYSMAN=1 ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE geopmread --cache
```

2024-10-16 18:10 UTC, bgeltz reviewed
Changes seem fine.  This should be tested on a L0 enabled system w/appropriate hardware, including building and deploying the service RPMs before we merge.

2024-10-16 20:59 UTC, cmcantalupo commented
```
$ geopmread GPU_POWER gpu 0
286.8566902140415
$ sudo geopmread
Warning: <geopm> LevelZero features require the environment variable setting "ZES_ENABLE_SYSMAN=1".
                 LevelZero features require the environment variable setting "ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE".
                 This process may corrupt the topology cache file if LevelZero enabled GPUs are present.
                 Run the following commands to fix:
                     sudo rm -f /run/geopm/geopm-topo-cache
                     sudo env ZES_ENABLE_SYSMAN=1 ZE_FLAT_DEVICE_HIERARCHY=COMPOSITE geopmread --cache
...
```

2024-10-16 23:09 UTC, bgeltz approved these changes

2024-10-16 23:09 UTC, merged