Makes geopmread/geopmwrite info uniform across IO Groups
geopm/geopm pull request #3660
Opened 2024-12-27 18:02 UTC by asmaalrawi

- Fixes #3025 

* Added units to LevelZeroIOGroup
* Expanded signal/control info string in LevelZeroIOGroup
* TODO: PlatformIO Group

2025-01-09 22:13 UTC, bgeltz commented on libgeopmd/src/LevelZeroIOGroup.hpp
> +		int m_units;
Please check the indentation here.  It looks off, but that might be GitHub.

2025-01-15 00:45 UTC, cmcantalupo commented on libgeopmd/src/LevelZeroIOGroup.cpp
> +        std::string result;
Kind of a nit, but would be easier to read if you used a std::ostringstream.

2025-01-15 00:48 UTC, cmcantalupo reviewed
Just a nit about using ostringstream

2025-01-23 00:46 UTC, asmaalrawi commented on libgeopmd/src/NVMLIOGroup.cpp
> +                                  M_UNITS_HERTZ,
Hertz isn't really throughput... do we want a new unit for throughput? M_UNITS_BPS ?

2025-01-24 02:16 UTC, cmcantalupo approved these changes, later dismissed
LGTM

2025-01-24 17:35 UTC, bgeltz requested changes
Where is "alias_for"

2025-01-24 17:35 UTC, bgeltz commented on docs/source/geopmread.1.rst
> +       units: seconds
```suggestion
       description: Time since the start of application profiling.
       alias_for: TIME::ELAPSED
       units: seconds
```

2025-01-24 17:35 UTC, bgeltz commented on integration/service/test/test_cli_info.sh
> +#!/bin/bash
integration/test_geopmio.py was written to capture these sorts of tests.
Why create a new harness and test script instead of integrating into test_geopmio.py?
This new test will not get picked up by the nightly test automation since it is not test_*.py

2025-01-24 17:35 UTC, bgeltz commented on libgeopmd/src/LevelZeroIOGroup.cpp
> -                m_signal_available[ds.first] = {ds.second.m_description + "\n    alias_for: " +
Where is "alias_for" injected for this IOGroup?
I see the code for injecting "alias_for" was not modified e.g. in MSRIOGroup.
Is this handled somewhere higher up the stack?
Probably a good thing to add to the test that verifies all signal/control information.

2025-01-24 18:44 UTC, asmaalrawi commented on libgeopmd/src/LevelZeroIOGroup.cpp
> -                m_signal_available[ds.first] = {ds.second.m_description + "\n    alias_for: " +
The alias_for was injected in two different places for the derivative signals and contained different bits of information. This one set the numerator + rate of change as alias and one further below aliased to the actual IOGroup derivative signal.

Before change:

```
GPU_POWER:
    description: Average GPU power over 40 ms or 8 control loop iterations.  Derivative signal based on LEVELZERO::GPU_ENERGY.
    alias_for: LEVELZERO::GPU_ENERGY rate of change
    alias_for: LEVELZERO::GPU_POWER
    units: watts
    aggregation: sum
    domain: gpu
    iogroup: LevelZeroIOGroup
```

After change:

```
GPU_POWER:
    description: Average GPU power over 40 ms or 8 control loop iterations.  Derivative signal based on LEVELZERO::GPU_ENERGY.
    alias_for: LEVELZERO::GPU_POWER
    units: watts
    aggregation: sum
    domain: gpu
    iogroup: LevelZeroIOGroup
```

2025-01-24 19:30 UTC, bgeltz commented on integration/service/test/test_cli_info.sh
> +#!/bin/bash
Direction is to move towards using these bash scripts for easier testing and potential documentation that can be shared to users.
Eventually the hope is that all tests in this file will be refactored into bash scripts that are invoked by test_bash_examples.py.
AR: Open an issue to track the refactor of test_geopmio.py into a bash script structure.

2025-01-24 19:30 UTC, bgeltz commented on libgeopmd/src/NVMLIOGroup.cpp
> +                                  M_UNITS_HERTZ,
We're going to table this until we can query it programmatically.  Then we'll revisit what the proper units are here.

2025-01-24 19:30 UTC, bgeltz commented on libgeopmd/src/TimeIOGroup.cpp
> +        if (!signal_name.compare("TIME")) {
```suggestion
        if (signal_name == "TIME") {
```

2025-01-24 19:38 UTC, bgeltz approved these changes

2025-01-24 19:39 UTC, cmcantalupo approved these changes

2025-01-24 19:46 UTC, merged