Add man page for geopmadmin tool
geopm/geopm pull request #892
Opened 2020-01-27 19:35 UTC by cmcantalupo

2020-01-27 19:44 UTC, dianarg requested changes
Any spec file changes needed?  Should this go into beta for now until the next release, or would it be better to move to beta only if it's not part of the release?

2020-01-27 19:44 UTC, dianarg commented on ronn/geopmadmin.1.ronn
> +
help and version?

2020-01-27 19:44 UTC, dianarg commented on ronn/geopmadmin.1.ronn
> +the set default and override values for the GEOPM runtime.  The tool
the set -> that set

2020-01-27 19:44 UTC, dianarg commented on ronn/geopmadmin.1.ronn
> +GEOPM requirements.
Might also want back link(s) to the part of the README that discusses these set up steps.

2020-01-27 19:44 UTC, dianarg commented on ronn/geopmadmin.1.ronn
> +**geopmagent(1)**
geopmlaunch(1) ?

2020-01-28 18:59 UTC, bakerbrandond commented on ronn/geopmadmin.1.ronn
> +configuration on the system.  When run with no arguments it will parse
output is assumed json.  should we be explicit here?

2020-01-28 19:17 UTC, cmcantalupo commented on ronn/geopmadmin.1.ronn
> +configuration on the system.  When run with no arguments it will parse
I was thinking more human readable:

GEOPM_AGENT: energy_efficient (default)
GEOPM_POLICY: /etc/geopm/policy.json (default)
GEOPM_PLUGIN_PATH: /opt/admin/geopm/plugin (override)

2020-01-28 19:19 UTC, bakerbrandond commented on ronn/geopmadmin.1.ronn
> +configuration on the system.  When run with no arguments it will parse
can I request an option for json so I can dump the output of the tool directly into a json object in python for the testing?

2020-01-29 00:08 UTC, dianarg approved these changes

2020-01-29 00:09 UTC, merged