Add scenarios for override settings
geopm/geopm pull request #896
Opened 2020-01-28 00:34 UTC by dianarg

2020-01-28 00:53 UTC, cmcantalupo reviewed
Seems like a good start.  I was thinking that we would name the scripts after the numbered step (e.g. setup_1.sh things may not break down exactly like that.

2020-02-03 21:44 UTC, bgeltz requested changes
A few little things.

2020-02-03 21:44 UTC, bgeltz commented on tutorial/admin/README.md
> +provides tools for launching and interacting with MPI applications. The slurm
s/slurm/SLURM

2020-02-03 21:44 UTC, bgeltz commented on tutorial/admin/README.md
> +    - Build an RPM to be used to install geopmpolicy on the compute nodes:
s/geopmpolicy/libgeopmpolicy

2020-02-03 21:44 UTC, bgeltz commented on tutorial/admin/README.md
> +only with the following:
s/only with/to contain

2020-02-03 21:44 UTC, bgeltz commented on tutorial/admin/README.md
> +    - Make sure that PlugStackConfig is not set.
This is OK imo.  If the admin wants to put the plugstack.conf somewhere other than the default, that's OK as long as libgeopm_spank.so is present in the file.

2020-02-03 21:44 UTC, bgeltz commented on tutorial/admin/setup_default_energy_efficient.sh
> +#   > srun --reservation=plugin_freq_cap geopmread MSR::PERF_CTL:FREQ board 0
Consider adding something that explains about the --reservation flag.  Otherwise I'd remove it.

2020-02-03 22:19 UTC, bgeltz approved these changes

2020-02-03 22:23 UTC, merged