Add composite signal support to PlatformIO.read_signal
geopm/geopm pull request #955
Opened 2020-02-22 01:18 UTC by bgeltz

Fixes #827.
Uses DifferenceCombinedSignal instead of Agg::difference.

2020-02-22 01:21 UTC, bgeltz commented
Let's talk a bit on Monday, but I don't see the benefit to this approach.

I think we're limiting the usefulness of DifferenceCombinedSignal by requiring it to have exactly 2 elements.

If we decide to go with this, I need to add a unit test for DifferenceCombined signal.

2020-02-22 01:23 UTC, bgeltz commented
Also, I'm not sure why, but the commits in the PR are in a different order than they are in my branch:

```
* d5b74b51 - (HEAD -> bgeltz-issue-827-dcs, bgeltz-public/bgeltz-issue-827-dcs) Use read_signal in geopmread (7 minutes ago) <Brad Geltz>
* 6f0d4cd6 - Add composite signal support to read_signal (7 minutes ago) <Brad Geltz>
* 907d4efb - Add DifferenceCombinedSignal (7 minutes ago) <Brad Geltz>
* 0d74b622 - Spell out PACKAGE for temperature (7 minutes ago) <Brad Geltz>
* e142c621 - (origin/dev, dev) Doxygen documentation and comments nice-to-have (26 hours ago) <Xunjin>
* 3b23bf65 - Removed C++ style comments from C source files (26 hours ago) <Xunjin>
* d63cbeac - Throw error for unknown policy names in json file (3 days ago) <Diana Guttman>
* 0b3ec6dd - Fix a potential bug where policies made of zeros would never be sent by TreeComm (3 days ago) <Diana Guttman>
* 78e6de29 - Add Reduce model region and clean up barrier model region (3 days ago) <Christopher M. Cantalupo>
* c72f5ef8 - Add a barrier model region (3 days ago) <Christopher M. Cantalupo>
```

2020-02-24 18:45 UTC, bgeltz commented on src/CombinedSignal.cpp
> +        if (values.size() != 2) {
Move DEBUG check up above if.

2020-02-24 18:45 UTC, bgeltz commented on src/PlatformIO.cpp
> +            if (signal_name.find("POWER") != std::string::npos) {
Be strict about the index == 0 here if we're sure this starts with "POWER...".

2020-02-25 00:34 UTC, dianarg requested changes

2020-02-25 00:34 UTC, dianarg commented on src/CombinedSignal.cpp
> +            throw Exception("PlatformIOImp::push_signal_temperature(): expected two values to subtract for temperature.",
error message is out of date

2020-02-25 00:34 UTC, dianarg commented on src/CombinedSignal.hpp
> +    ///        difference of another signal.
difference between two signals

2020-02-25 00:53 UTC, dianarg submitted a review, later dismissed

2020-02-25 00:57 UTC, dianarg requested changes
👎 
test if this will be wiped out by force push

2020-02-25 01:02 UTC, dianarg approved these changes
👍

2020-02-25 01:30 UTC, merged

2021-07-07 23:15 UTC, cmcantalupo commented on src/PlatformIO.cpp
> +            if (signal_name.find("POWER") == 0) {
Should be

```
if (signal_name.find("POWER") != std::string::npos) {
```